spring:
  application:
    name: gurms-server

# gurms-app已经定义了port,这里定义无效
#server:
#  port: 6000        

eureka:
  client:
    # 是否启用eureka客户端。默认true
    enabled: true # 本地调试时，若不想启动eureka，可配置false即可，而不需要注释掉@EnableDiscoveryClient这么麻烦。
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/

feign:
  hystrix:
    enabled: true

