spring:
  application:
    name: gurms-server

server:
  port: 5100        # 引入的gurms-app已经定义了port 8080，这里定义无效

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/

feign:
  hystrix:
    enabled: true

